version: "3.8"
services:
  minio:
    container_name: minio_cont
    image: quay.io/minio/minio:RELEASE.2024-01-18T22-51-28Z
    #command: server --console-address ":9001" http://minio/data
    command: server /data --address ":${S3_PORT}" --console-address ":${S3_WEB_CLIENT_PORT}"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
      MINIO_DEFAULT_BUCKETS: ${S3_BUCKET}
      MINIO_ADDRESS: ${S3_PORT}
      MINIO_CONSOLE_ADDRESS: ${S3_WEB_CLIENT_PORT}
    ports:
      - ${S3_PORT}:${S3_PORT}
      - ${S3_WEB_CLIENT_PORT}:${S3_WEB_CLIENT_PORT}
    # network_mode: host
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "${S3_FILE_VOLUME_PATH}:/data"

  minio_volume:
    driver: local
    driver_opts:
      type: none
      device: ${S3_FILE_VOLUME_PATH}
